- thoth/lab/utils.py
```
def str_join(df: pd.DataFrame, cols: list, sep: str = ''):
"""Combine two or more string columns into one joining whem with `sep`."""
```
modified:   thoth/lab/utils.py
> Add str_join function to utils module

- thoth/lab/jupyter.py
```python
def link_css(stylesheet: str):
"""Link CSS stylesheet."""
```
```python
def link_js(lib: str):
"""Link JavaScript library."""
```
```python
def load_style(style: str):
"""Create new style element and add it to the page."""
```
```python
def load_script(script: str):
"""Create new script element and add it to the page."""
```
<br>
new file:   thoth/lab/jupyter.py
> Common jupyter utilities to customize environment

- thoth/lab/viz/__init__.py
- thoth/lab/viz/js/__init__.py
- thoth/lab/viz/js/assets/css/d3.css
- thoth/lab/viz/js/dynamic/__init__.py
- thoth/lab/viz/js/static/__init__.py
- thoth/lab/viz/js/static/templates/diagonal.js
Depends on #96 
To test out, check out the example:
https://gist.github.com/CermakM/1fcd03af3d2516cce63ed0f3bb4a45bd
new file:   thoth/lab/viz/__init__.py
new file:   thoth/lab/viz/js/__init__.py
new file:   thoth/lab/viz/js/assets/css/d3.css
new file:   thoth/lab/viz/js/dynamic/__init__.py
new file:   thoth/lab/viz/js/static/__init__.py
new file:   thoth/lab/viz/js/static/templates/diagonal.js
> Introduce dependency vizualization using d3.js

- setup.py
- use find_packages() in setup.py and prefix them with 'thoth.'
namespace
modified:   setup.py
> Make sure all packages are installed

- Pipfile
- Pipfile.lock
- requirements.txt
- thoth/lab/viz/__init__.py
- thoth/lab/viz/assets/css/d3.css
- thoth/lab/viz/assets/js/dynamic/diagonal.js
- thoth/lab/viz/assets/js/static/diagonal.js
Jupyter-require is rapidly developing and some breaking changes have been introduced during the latest releases. This PR also makes full use of its execution mechanism and output persistence.
Additional changes:
- sync requirement files
- add cufflinks and matplotlib to Pipfile
- Improve some stylistic issues regarding our plots, like centring and zooming.
> Account for jupyter-require API changes

- thoth/lab/underscore.py
- thoth/lab/utils.py
Create the `underscore` module
Module `underscore` contains common pandas operations and utilities and
creates pandas api extensions `_` as the accessor to those utilities.
- move `str_join` method to that module
> Underscore module

- thoth/lab/utils.py
modified:   thoth/lab/utils.py
> Fix incorrect defaults and unnecessary check

- thoth/lab/underscore.py
modified:   thoth/lab/underscore.py
> Add Underscore accessor for pd.Series as well

- thoth/lab/underscore.py
modified:   thoth/lab/underscore.py
> Pandas utilities to flatten columns with nested records

- thoth/lab/graph.py
modified:   thoth/lab/graph.py
> Utilities for dependency graph traversals

- Pipfile
> Add autopep8 to dev-dependencies for vscode

- thoth/lab/convert.py
- thoth/lab/utils.py
modified:   thoth/lab/utils.py
> Jupyter Notebook utilities for text visualization

- Pipfile
- Pipfile.lock
- thoth/lab/inspection.py
- thoth/lab/underscore.py
- thoth/lab/utils.py
[summary]
- new module `inspection`
- extended functionality of the `underscore` module
- some of the functions moved to the `utils` module
new file:   thoth/lab/inspection.py
modified:   Pipfile
modified:   Pipfile.lock
modified:   thoth/lab/underscore.py
modified:   thoth/lab/utils.py
> Move functionality from Amun Inspection notebook

- .coafile
- .thoth.yaml
- thoth/lab/convert.py
- thoth/lab/graph.py
- thoth/lab/inspection.py
modified:   .coafile
modified:   .thoth.yaml
modified:   thoth/lab/convert.py
modified:   thoth/lab/graph.py
modified:   thoth/lab/inspection.py
> Fix coala issues

- thoth/lab/graph.py
> Remove Gremlin imports

- requirements.txt
Comments were unintentional and probably added by vim automatically.
> Fix unintentional comments in requirements.txt

- thoth/lab/underscore.py
modified:   thoth/lab/underscore.py
> Fix incorrect indexing in `groupby` method

- thoth/lab/inspection.py
> Corrected measurement unit and typo

- Pipfile
- Pipfile.lock
- requirements.txt
- thoth/lab/inspection.py
- thoth/lab/inspection_report.py
- Added new functions for analysis of inspection results and correlations between results.
- Created report function to automatically analyze important features of the inspection results. 
- Created summary functions to identify differences across different inspection batches.
> New functions for inspection results and report functions

- thoth/lab/inspection.py
- thoth/lab/inspection_report.py
Depends-On: https://github.com/thoth-station/storages/pull/998
- Improved readability
- Standardized naming
- Improved functions generalization
- Added `save_results` flag
- Added violin plots
- Added `project_folder` flag
> Modify all functions for templates and Insert new features

- requirements.txt
> Modify requirements.txt

- requirements.txt
> remove constraint on plotly

- thoth/lab/adviser.py
> Methods to analyze adviser results

- thoth/lab/inspection.py
- thoth/lab/inspection_report.py
> Correct minor errors in functions

- Pipfile
- Pipfile.lock
> Substitute-package

- thoth/lab/adviser.py
> Move iplot initilization which is only for running in notebook

- requirements.txt
> Add missing package to requirements.txt

- README.rst
- setup.py
Otherwise the release pipelne fails
> Fixes needed to make the release happen

- thoth/lab/adviser.py
> Add check for CVE messages

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/major-release.md
- .github/ISSUE_TEMPLATE/minor-release.md
- .github/ISSUE_TEMPLATE/patch-release.md
- .github/PULL_REQUEST_TEMPLATE.md
> Add github templates

- thoth/lab/common.py
- thoth/lab/solver.py
Introduce methods to explore solver dataset
> Add solver specific functions

- thoth/lab/inspection.py
> Correct docstring

- thoth/lab/__init__.py
- thoth/lab/adviser.py
- thoth/lab/common.py
- thoth/lab/graph.py
- thoth/lab/inspection.py
- thoth/lab/solver.py
- thoth/lab/viz/__init__.py
Adjust methods for aggregation and plotting
> Adjust methods for plots and aggregation

- thoth/lab/adviser.py
- thoth/lab/common.py
> Add check on retrieval

- .thoth.yaml
update the maintainer for release of thoth-lab
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
> update the maintainer for release of thoth-lab

- Pipfile.lock
- thoth/lab/adviser.py
- thoth/lab/common.py
- thoth/lab/inspection.py
- thoth/lab/security.py
- thoth/lab/solver.py
Introduce security classes and methods to analyze SI-analyzers outputs.
> Introduce security indicators analysis classes

- Pipfile
- Pipfile.lock
- thoth/lab/common.py
- thoth/lab/security.py
- thoth/lab/solver.py
Missing dependency
Unify class for SI
Adjust plots
Add tag release
> Introduce security

- thoth/lab/common.py
- thoth/lab/inspection.py
> add store for inspection retrieval

- thoth/lab/common.py
> Correct SyntaxError

- thoth/lab/common.py
- thoth/lab/security.py
Add method to aggregate SI score
Correct issue with instantiation
> Add methods for aggreagaation and correct instantiation

- Pipfile
- requirements.txt
```
Collecting thoth-lab==0.2.4
Using cached thoth-lab-0.2.4.tar.gz (43 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... error
ERROR: Command errored out with exit status 1:
command: /usr/bin/python3 /home/fmurdaca/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpepoh0v_f
cwd: /tmp/pip-install-xiojbpp1/thoth-lab
Complete output (20 lines):
Traceback (most recent call last):
File "/home/fmurdaca/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
main()
File "/home/fmurdaca/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
json_out['return_val'] = …
```
> Add package

- MANIFEST.in
> Include requirements.txt in distribution

- README.rst
> Minor improvements to docs

- Pipfile
- Pipfile.lock
Fixes: https://github.com/thoth-station/lab/issues/255
> add constraint on ipython due to new major release
